import { readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { ffmpeg } from './ffmpeg.js';

/** Cover sizes generated by the pipeline (WebP). */
export const COVER_SIZES = [64, 300, 1200] as const;

/**
 * Extracts embedded cover art (attached_pic stream) to a Buffer via ffmpeg.
 * Returns null when the file has no embedded art. music-metadata is tried
 * first by the worker; this is the fallback for exotic containers.
 */
export async function extractEmbeddedCover(
  filePath: string,
  tmpDir: string,
): Promise<Buffer | null> {
  const outPath = path.join(tmpDir, 'embedded-cover.jpg');
  try {
    await new Promise<void>((resolve, reject) => {
      ffmpeg(filePath)
        .outputOptions(['-map 0:v:0', '-frames:v 1', '-an'])
        .output(outPath)
        .on('error', (err: Error) => reject(err))
        .on('end', () => resolve())
        .run();
    });
    return await readFile(outPath);
  } catch {
    return null;
  } finally {
    await rm(outPath, { force: true }).catch(() => undefined);
  }
}
